# environment.yml
name: my-env
channels:
 - conda-forge
 - defaults
dependencies:
 - pandas=2.2.2
 - pandera=0.20.4
 - python=3.11
 - numpy=2.1.3
 - pandas=2.2.3
 - pip
 - pip:
    - deepchecks==0.18.1